### ISSUE TITLE
Base content a duplicated variable caused unexpected bug during repeated testing

### ISSUE THREAD

**Issue by alan-cugler** [OlavStornes/ModBuddy#14]
The mods starting `base content` variable strikes me as something that should be hidden from the user as it is always required to be loaded first so mods can then make layered changes on those files. That being said this was missing from multiple scrub testing runs, and it took me three hours to figure out it was missing from the mods list.
https://github.com/OlavStornes/ModBuddy/blob/f049634c512c7d3e1666c5965f9ee5d620dce705/main.py#L222-L224

When looking at where the error was coming from, I realized a null value for the base content path seems silly since the path is available  in the `game_mod_folder` variable. So not knowing which one of my testing resets messed up the mods dictionary leads me to ask if `target_folder` should be set to the `game_mod_folder` and not extracted from the `mod_list` dictionary?
https://github.com/OlavStornes/ModBuddy/blob/f049634c512c7d3e1666c5965f9ee5d620dce705/modpack.py#L39-L44

**Comment by OlavStornes** [comment]
Thanks for taking the time to debug. Do you have any suspicions on why your base content path returned null? I haven't actually tried to purge my own setup so often, but i'm pretty sure i haven't had this problem before.

The reason that `game_mod_folder` needs to be a separate entity from a mod entry is to handle removal of mods without leaving behind artifacts. When applying a set of mods (including "base content"), _Everything inside `game_mod_folder` is deleted_ (technically it is unlinked, since modbuddy uses hard links to avoid duplication of data). After this, everything is linked back together, creating a folder with the mods included.

However, an alternative implementation for handling the base content isn't a bad idea.

**Comment by alan-cugler** [comment]
I think there is a step you have in first startup with either ModBuddy in general, adding a game, or making a new profile. This isnt reoccurring later if removed. So I assume I removed the json, and then continued on with my experiment. But since I wiped a step that is only initial and not rechecked it never populated the base_content again.

**Comment by OlavStornes** [comment]
It's probably when adding a game (`create_new_game()`), but the path to base content should be retrieved at the same time as it is written. It could be a bug when the file is partially modified or something akin to that, but I can't say that for certain without some more digging.
